### ISSUE TITLE
Error on armv8l

### ISSUE THREAD

**Issue by arc1887** [mcbegamerxx954/draco-injector#12]
If it failed due to 'os error 17' then it should work the next time.
If it failed due to 'Unaligned sh_offset value'

**Comment by CallMeSoumya2063** [comment]
Okay you used my script, you should have mentioned that, what's the specific error did you get? OS error 17 or Unaligned sh_offset value? If you don't understand what I'm asking to send you then just send the screenshot.

**Comment by mcbegamerxx954** [comment]
Im working on this right now, but the time of the fix depends on people that are not me

**Comment by mcbegamerxx954** [comment]
Fixed
