### ISSUE TITLE
Unalligned error

### ISSUE THREAD

**Issue by robuxman06** [mcbegamerxx954/draco-injector#13]
![Screenshot_20240713_201650_Termux](https://github.com/user-attachments/assets/1cd4a670-58fa-4926-8a34-dd0eeba021e8)

**Comment by robuxman06** [comment]
I would like to know if there is a current fix to this?

**Comment by atashi764** [comment]
take a look on these

https://github.com/mcbegamerxx954/draco-injector/issues/7#issuecomment-2206930026

https://github.com/mcbegamerxx954/draco-injector/issues/12#issuecomment-2226887863

https://github.com/mcbegamerxx954/draco-injector/issues/11#issuecomment-2206947155

he is working on fixing that.

**Comment by atashi764** [comment]
the fix for now would be not using the injector and using manual dex method instead which you can find in the mcbe shader redirector repo

**Comment by mcbegamerxx954** [comment]
Hey, just so everyone knows, this issue was fixed a long time ago with a injector update
