### ISSUE TITLE
.

### ISSUE THREAD

**Issue by NesiaID** [mcbegamerxx954/draco-injector#15]

**Comment by CallMeSoumya2063** [comment]
> ![IMG_20240918_203441](https://github.com/user-attachments/assets/4c725ab1-4ae6-4d76-9b6e-ff52e188859c)

Ok but what's the error? It should be a few lines before the part you sent

Also which version of Minecraft are you patching, and for what architecture? 32 bit or 64 bit?

**Comment by NesiaID** [comment]
> > ![IMG_20240918_203441](https://private-user-images.githubusercontent.com/181977169/368590616-4c725ab1-4ae6-4d76-9b6e-ff52e188859c.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY3MDQ3MDYsIm5iZiI6MTcyNjcwNDQwNiwicGF0aCI6Ii8xODE5NzcxNjkvMzY4NTkwNjE2LTRjNzI1YWIxLTRhZTYtNGQ3Ni05YjZlLWZmNTJlMTg4ODU5Yy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxOVQwMDA2NDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZjc0M2EzYWJmMzUwYTMxOWRlYjQ2ODRjYTVkNjk5ZGY3YWU2NTBkOWU0OGFkOWZhZTA4ZmIzMzAyMzhjY2NlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ueDL5gm7EuHFVDPSe5YHjWSq8pkXsFbB1M5Znq6EPKU)
> 
> Oke, tapi apa kesalahannya? Seharusnya ada beberapa baris sebelum bagian yang Anda kirim
> 
> Versi Minecraft mana yang Anda patch, dan untuk arsitektur apa? 32 bit atau 64 bit?

**Comment by NesiaID** [comment]
That's 64bit

**Comment by NesiaID** [comment]
> Itu 64bit ![Tangkapan layar_20240919_071219](https://private-user-images.githubusercontent.com/181977169/368782132-8ec3c51e-1112-4aac-a4e8-7a0e9fa52ccc.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY3MDYyMjcsIm5iZiI6MTcyNjcwNTkyNywicGF0aCI6Ii8xODE5NzcxNjkvMzY4NzgyMTMyLThlYzNjNTFlLTExMTItNGFhYy1hNGU4LTdhMGU5ZmE1MmNjYy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxOVQwMDMyMDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMTM1NTgxZWQ2ZDg3Y2ZhOWM3ZTc0NzE3MTNiMWE1NTlhNmJkNjU3MDE3NDVkNzUwZjIzMDNjM2M0OGM5M2FjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Ut8ovd9BgyqgT4DG5Sj8Tfj5ad2WVVzH9zjMslz_b1g)



> Itu 64bit ![Tangkapan layar_20240919_071219](https://private-user-images.githubusercontent.com/181977169/368782132-8ec3c51e-1112-4aac-a4e8-7a0e9fa52ccc.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY3MDYyMjcsIm5iZiI6MTcyNjcwNTkyNywicGF0aCI6Ii8xODE5NzcxNjkvMzY4NzgyMTMyLThlYzNjNTFlLTExMTItNGFhYy1hNGU4LTdhMGU5ZmE1MmNjYy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxOVQwMDMyMDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMTM1NTgxZWQ2ZDg3Y2ZhOWM3ZTc0NzE3MTNiMWE1NTlhNmJkNjU3MDE3NDVkNzUwZjIzMDNjM2M0OGM5M2FjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Ut8ovd9BgyqgT4DG5Sj8Tfj5ad2WVVzH9zjMslz_b1g)

but for 32bit it works
![Screenshot_20240919_073152](https://github.com/user-attachments/assets/12c7c33e-d2ec-4ca9-9a51-f1f32d0b28cb)

**Comment by NesiaID** [comment]
![Screenshot_20240919_073449](https://github.com/user-attachments/assets/bbfe75cc-9e43-4d11-94f8-dfd17642a42e)
.
But for 32bit it works
