### ISSUE TITLE
Dependencies? 

### ISSUE THREAD

**Issue by atashi764** [mcbegamerxx954/draco-injector#3]
I just tried it worked fine on Linux but the problem is, the output got only AndroidManifest.xml changed nothing else. 

Is there something that I am missing?

**Comment by mcbegamerxx954** [comment]
The binary itself has absolutely no dependencies (like things that you need to apt install)
however, it should say something like "patching minecraft aarch64", where it downloads the lib for the arch and patches that arch of mcbe to use it

**Comment by atashi764** [comment]
![image](https://github.com/mcbegamerxx954/draco-injector/assets/40156662/7bb43638-6794-4741-b3b6-fe4b163d2789)
i am not sure if anything is wrong here, i downloaded unknown gnu thingy.

and there is no additional dex in libs folder

**Comment by mcbegamerxx954** [comment]
> ![image](https://private-user-images.githubusercontent.com/40156662/329866037-7bb43638-6794-4741-b3b6-fe4b163d2789.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1MzQ3NTEsIm5iZiI6MTcxNTUzNDQ1MSwicGF0aCI6Ii80MDE1NjY2Mi8zMjk4NjYwMzctN2JiNDM2MzgtNjc5NC00NzQxLWIzYjYtZmU0YjE2M2QyNzg5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEyVDE3MjA1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU1ODgwZmE3YWMwMjg0ZjgzZGRlMGVhNmNjZGEzZjExZjZhYzMxNTNkNzU1YzNkYTAwODFkNTEyODkxYzhjN2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.H1tTuLMed_kY2dW9zV1QEtChwlvHocUvZtS0txhLXow) i am not sure if anything is wrong here, i downloaded unknown gnu thingy.
> 
> and there is no additional dex in libs folder

Check if the apk has a lib folder and tell me what folders are there, it searches for libminecraftpe.so file in those folders to patch

**Comment by mcbegamerxx954** [comment]
Anything?

**Comment by atashi764** [comment]
![Screenshot_20240513-072845_MiXplorer](https://github.com/mcbegamerxx954/draco-injector/assets/40156662/87753bf2-3d74-44b7-90c3-ea6ecb20dbd5)

it has these folders. even though the patcher didn't work but lib stuff from your linking repo did work both for 1.20.73 and 1.20.81 (dex method)

**Comment by mcbegamerxx954** [comment]
I found the bug right now, check v0.1.3

**Comment by atashi764** [comment]
![image](https://github.com/mcbegamerxx954/draco-injector/assets/40156662/c4da8b47-732d-4c2b-bf82-a56877025b59)
it worked this time. 

thanks
