### ISSUE TITLE
Make app name argument (Minecraft (whar)) optional

### ISSUE THREAD

**Issue by atashi764** [mcbegamerxx954/draco-injector#5]
cause why not?

**Comment by atashi764** [comment]
kinda off topic. but this repo seriously needs more publicity. it's really better than materialBinLoader. i just find it not so "open-source" they are seen releasing their own patched apk but not updating source. also that's simply not an universal solution for all versions. where this redirector is. (ig)

kudos to dev :+1:

**Comment by mcbegamerxx954** [comment]
Done 

> kinda off topic. but this repo seriously needs more publicity. it's really better than materialBinLoader. i just find it not so "open-source" they are seen releasing their own patched apk but not updating source. also that's simply not an universal solution for all versions. where this redirector is. (ig)
> 
> kudos to dev 👍

Ty
