### ISSUE TITLE
Add music removal feature as an argument / Make the injector run with a single command (for better compatibility with community made scripts)

### ISSUE THREAD

**Issue by atashi764** [mcbegamerxx954/draco-injector#9]
adding something like -nomusic should directly remove music instead of asking user.

also adding something like -noprompt will ignore the disclaimer thingy. so scripts from people like @CallMeSoumya2063 can be simplified more. (if user adds -noprompt but not -nomusic, it will proceed to patch apk without removing music)

**Comment by mcbegamerxx954** [comment]
Fixed by removing no songs interactive prompt (might add it back soon though) + making the shader compatibility tip shorter
